
--1
CREATE TABLE Customers_142 (
CUSTOMERID NUMBER (10) PRIMARY KEY, FIRSTNAME VARCHAR (50),
LASTNAME VARCHAR (50)
);
INSERT INTO Customers_142 (CUSTOMERID, FIRSTNAME, LASTNAME) VALUES (1, 'Sara', 'Davis'); 
INSERT INTO Customers_142 (CUSTOMERID, FIRSTNAME, LASTNAME) VALUES (2, 'Rumi', 'Shah'); 
INSERT INTO Customers_142 (CUSTOMERID, FIRSTNAME, LASTNAME) VALUES (3, 'Paul', 'Johnson'); 
INSERT INTO Customers_142 (CUSTOMERID, FIRSTNAME, LASTNAME) VALUES (4, 'Samuel', 'Martinez');
INSERT INTO Customers_142 (CUSTOMERID, FIRSTNAME, LASTNAME) VALUES (5, 'Roshan', 'Shrestha');

--2
CREATE TABLE Orders_142 (
ORDERID NUMBER (10) PRIMARY KEY,
CUSTOMERID NUMBER (10),
ORDERDATE DATE,
ORDERAMOUNT NUMBER (10, 2),
FOREIGN KEY (CUSTOMERID) REFERENCES Customers_142(CUSTOMERID)
);
INSERT INTO Orders_142 (ORDERID, CUSTOMERID, ORDERDATE, ORDERAMOUNT) VALUES (1, 1, TO_DATE('01-SEP-16', 'DD-MON-YY'), 10);
INSERT INTO Orders_142 (ORDERID, CUSTOMERID, ORDERDATE, ORDERAMOUNT) VALUES (2, 2, TO_DATE('02-SEP-16', 'DD-MON-YY'), 12.5);
INSERT INTO Orders_142 (ORDERID, CUSTOMERID, ORDERDATE, ORDERAMOUNT) VALUES (3, 2, TO_DATE('03-SEP-16', 'DD-MON-YY'), 18);
INSERT INTO Orders_142 (ORDERID, CUSTOMERID, ORDERDATE, ORDERAMOUNT) VALUES (4, 3, TO_DATE('15-SEP-16', 'DD-MON-YY'), 20);
INSERT INTO Orders_142 (ORDERID, CUSTOMERID, ORDERDATE, ORDERAMOUNT) VALUES (5, 4, TO_DATE('21-NOV-20', 'DD-MON-YY'), 20);

--3
CREATE TABLE Refunds_142 (
REFUNDID NUMBER (10) PRIMARY KEY,
ORDERID NUMBER (10),
REFUNDDATE DATE,
REFUNDAMOUNT NUMBER (10, 2),
FOREIGN KEY (ORDERID) REFERENCES Orders_142(ORDERID)
);
INSERT INTO Refunds_142 (REFUNDID, ORDERID, REFUNDDATE, REFUNDAMOUNT) VALUES (1, 1, TO_DATE('02-SEP-16', 'DD-MON-YY'), 5);
INSERT INTO Refunds_142 (REFUNDID, ORDERID, REFUNDDATE, REFUNDAMOUNT) VALUES (2, 3, TO_DATE('18-SEP-16', 'DD-MON-YY'), 18);


--4
SELECT c.CUSTOMERID, c.FIRSTNAME,
c.LASTNAME, o.ORDERID, o.ORDERDATE, o.ORDERAMOUNT
FROM Customers_142 c
INNER JOIN Orders_142 o ON c.CUSTOMERID = o.CUSTOMERID;

--5
SELECT c.FIRSTNAME, c.LASTNAME,
o.ORDERDATE, o.ORDERAMOUNT, r.REFUNDDATE,
r.REFUNDAMOUNT FROM Customers_142 c
INNER JOIN Orders_142 o ON c.CUSTOMERID = o.CUSTOMERID INNER JOIN Refunds_142 r ON o.ORDERID = r.ORDERID;

--6
SELECT c.CUSTOMERID, c.FIRSTNAME, c.LASTNAME, o.ORDERID,
o.ORDERDATE,
o.ORDERAMOUNT,
r.REFUNDID,
r.REFUNDDATE,
r.REFUNDAMOUNT
FROM Customers_142 c
LEFT JOIN Orders_142 o ON c.CUSTOMERID = o.CUSTOMERID LEFT JOIN Refunds_142 r ON o.ORDERID = r.ORDERID;